import { useState, type FormEvent } from 'react';
import { ArrowRight, Check, ArrowLeft } from 'lucide-react';
import { Button } from './ui/Button';
import { Input, Select, Field } from './ui/Fields';
import { Section, Callout } from './ui/Surfaces';
import { sectors, reasons, shifts, money, type Refund } from '../lib/domain';
export function RefundForm({ original, refunds, saving, error, onSave, onCancel }: { original?: Refund; refunds: Refund[]; saving: boolean; error: string; onSave: (data: Partial<Refund>) => void; onCancel: () => void }) {
  const [step, setStep] = useState(0);
  const [data, setData] = useState<Partial<Refund>>(original ?? { requester: '', institution: 'EJND_GRAD', sector: 'Graduação', method: 'pix', lyceumConfirmed: false, shift: 'Noturno', notes: '', email: '' });
  const [amount, setAmount] = useState(original ? (original.amount / 100).toFixed(2).replace('.', ',') : '');
  const change = (name: keyof Refund, value: unknown) => setData(d => ({ ...d, [name]: value }));
  const input = (name: keyof Refund, label: string, required = true, type = 'text', help?: string) => <Field label={label} required={required} help={help}>{id => <Input id={id} required={required} type={type} value={String(data[name] ?? '')} onChange={e => change(name, e.target.value)} maxLength={200}/>}</Field>;
  const select = (name: keyof Refund, label: string, options: string[]) => <Field label={label} required>{id => <Select id={id} required value={String(data[name] ?? '')} onChange={e => change(name, e.target.value)}><option value="">Selecione</option>{options.map(o => <option key={o}>{o}</option>)}</Select>}</Field>;
  const cents = Math.round(Number(amount.replace(/\./g, '').replace(',', '.')) * 100);
  const similar = refunds.filter(r => r.id !== original?.id && r.ra.toLowerCase() === data.ra?.trim().toLowerCase() && r.amount === cents && r.status !== 'encerrado');
  function submit(e: FormEvent) { e.preventDefault(); if (step === 0) { setStep(1); return; } onSave({ ...data, amount: cents }); }
  return <form onSubmit={submit} className="flex flex-col"><div className="space-y-6 p-5"><div className="flex items-center gap-3 text-[12px] text-ink-3"><span className={step === 0 ? 'font-semibold text-ink' : ''}>1. Solicitação</span><ArrowRight className="h-3 w-3"/><span className={step === 1 ? 'font-semibold text-ink' : ''}>2. Pagamento</span></div>
    {original?.pendingReason && <Callout><strong className="font-semibold">Ajuste solicitado</strong><p className="mt-1">{original.pendingReason}</p></Callout>}
    {step === 0 ? <><Section title="Aluno e instituição"><div className="grid gap-4 sm:grid-cols-2">{input('requester', 'Nome do solicitante')}{input('student', 'Nome do aluno')}{input('responsible', 'Nome do responsável')}{input('ra', 'RA')}{input('course', 'Curso')}{input('institution', 'Instituição')}{select('sector', 'Setor solicitante', sectors)}{select('shift', 'Turno / modalidade', shifts)}</div></Section><Section title="Devolução"><div className="grid gap-4 sm:grid-cols-2"><Field label="Valor a devolver" required>{id => <Input id={id} required inputMode="decimal" placeholder="0,00" value={amount} pattern="[0-9.,]+" onChange={e => setAmount(e.target.value)}/>}</Field>{select('reason', 'Motivo', reasons)}{input('lyceumReference', 'Referência da devolução no Lyceum', true, 'text', 'Identificador único da operação, usado para evitar duplicidade.')}{input('notes', 'Observação', false)}</div>{similar.length > 0 && <Callout>Existe outro pedido para este RA e valor: {similar.map(r => r.protocol).join(', ')}. Confira antes de cadastrar uma nova solicitação.</Callout>}<label className="flex items-start gap-3 text-[14px] font-medium leading-relaxed text-[var(--crit-ink)]"><input type="checkbox" required checked={!!data.lyceumConfirmed} onChange={e => change('lyceumConfirmed', e.target.checked)} className="mt-0.5 h-4 w-4 accent-[var(--brand)]"/>Confirmo que já registrei a solicitação na aba de devolução do Lyceum e conferi o valor do crédito.</label></Section></> : <><Section title="Dados para pagamento"><div className="grid gap-4 sm:grid-cols-2"><Field label="Forma de pagamento" required>{id => <Select id={id} value={data.method} onChange={e => change('method', e.target.value)}><option value="pix">Pix</option><option value="conta">Transferência bancária</option></Select>}</Field>{input('bank', 'Banco de destino')}{input('holder', 'Nome do correntista')}{input('holderCpf', 'CPF do correntista')}{data.method === 'pix' ? input('pix', 'Chave Pix') : <>{input('agency', 'Agência')}{input('account', 'Conta com dígito')}</>}</div></Section><Section title="Contato"><div className="grid gap-4 sm:grid-cols-2">{input('email', 'E-mail do aluno ou responsável', false, 'email', 'Opcional nesta apresentação. Necessário para o envio por e-mail.')}</div></Section><Callout><span className="font-medium">{data.student}</span> · {money(cents || 0)}<br/>O Financeiro receberá o pedido para conferência. Data e solicitante serão registrados no pedido.</Callout></>}
    {error && <p role="alert" className="rounded-xl bg-warn-soft p-3 text-[13px] text-warn-ink">{error}</p>}</div><footer className="flex items-center justify-between gap-3 border-t border-hairline bg-surface-2/60 px-5 py-3.5"><Button onClick={step ? () => setStep(0) : onCancel} variant="ghost">{step ? <><ArrowLeft className="h-4 w-4"/>Voltar</> : 'Cancelar'}</Button><Button type="submit" variant="primary" disabled={saving}>{saving ? 'Salvando…' : step ? <><Check className="h-4 w-4"/>{original ? 'Salvar e reenviar' : 'Cadastrar solicitação'}</> : <>Continuar<ArrowRight className="h-4 w-4"/></>}</Button></footer></form>;
}
