import { useCallback, useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import { ArrowDownLeft, Bell, CheckCheck, ChevronRight, CircleCheck, ClipboardList, Clock3, FileText, Inbox, LayoutList, Menu, Moon, Plus, RefreshCw, Search, Sun, X } from 'lucide-react';
import { Button } from './components/ui/Button';
import { Card, Callout, Section } from './components/ui/Surfaces';
import { Select } from './components/ui/Fields';
import { Avatar, StatusBadge } from './components/ui/Badges';
import { Overlay } from './components/ui/Overlay';
import { RefundForm } from './components/RefundForm';
import { RefundDetail } from './components/RefundDetail';
import { profiles, sectors, money, date, dateTime, owner, weekdays, closed, amountColor, type Refund, type Profile } from './lib/domain';
import { pageVariants, press, spring, toastVariants } from './lib/motion';
type View = 'all' | 'done';
export default function App() {
  const [profile, setProfile] = useState<Profile>(profiles[0]), [refunds, setRefunds] = useState<Refund[]>([]), [seenAt, setSeenAt] = useState('');
  const [loading, setLoading] = useState(true), [loadError, setLoadError] = useState(''), [view, setView] = useState<View>('all'), [filter, setFilter] = useState('all'), [sector, setSector] = useState('all'), [search, setSearch] = useState('');
  const [selected, setSelected] = useState<string | null>(null), [form, setForm] = useState<'new' | Refund | null>(null), [notices, setNotices] = useState(false), [guide, setGuide] = useState(false), [mobileMenu, setMobileMenu] = useState(false);
  const [saving, setSaving] = useState(false), [error, setError] = useState(''), [toast, setToast] = useState(''), [dark, setDark] = useState(document.documentElement.classList.contains('dark'));
  const api = useCallback(async (path: string, method = 'GET', body?: unknown) => { const res = await fetch(path, { method, headers: { 'Content-Type': 'application/json', 'Accept': 'application/json', 'X-Profile': profile.id }, cache: 'no-store', credentials: 'same-origin', ...(body ? { body: JSON.stringify(body) } : {}) }); const contentType = res.headers.get('content-type') || ''; if (!contentType.includes('application/json')) throw new Error('A resposta do servidor não está disponível. Atualize a página e tente novamente. Se persistir, avise a equipe técnica.'); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Não foi possível concluir.'); return data; }, [profile.id]);
  const refresh = useCallback(async () => { try { const data = await api('/api/refunds'); setRefunds(data.refunds); setSeenAt(data.seenAt); setLoadError(''); } catch (e) { setLoadError((e as Error).message); } finally { setLoading(false); } }, [api]);
  useEffect(() => { let alive = true; void api('/api/bootstrap', 'POST').then(() => { if (alive) return refresh(); }).catch(e => { if (alive) { setLoadError(e.message); setLoading(false); } }); const interval = setInterval(() => { if (document.visibilityState === 'visible') void refresh(); }, 15000); return () => { alive = false; clearInterval(interval); }; }, [api, refresh]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 4000); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => { const mc = (document as Document & { modelContext?: { registerTool: (tool: unknown, options: { signal: AbortSignal }) => Promise<void> } }).modelContext; if (!mc?.registerTool) return; const life = new AbortController(); void Promise.resolve(mc.registerTool({ name: 'filter_refunds', title: 'Filtrar devoluções', description: 'Mostra as devoluções que correspondem a um nome, RA ou protocolo. Não altera registros.', inputSchema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'], additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: false }, execute: async (input: unknown) => { if (!input || typeof input !== 'object' || !('query' in input) || typeof input.query !== 'string') throw new Error('query deve ser texto'); setSearch(input.query); setView('all'); setFilter('all'); setSector('all'); await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))); return { query: input.query }; } }, { signal: life.signal })).catch(() => {}); return () => life.abort(); }, []);
  const active = refunds.filter(r => !closed(r));
  const base = view === 'done' ? refunds.filter(closed) : refunds;
  const filtered = useMemo(() => base.filter(r => (filter === 'all' || r.status === filter) && (sector === 'all' || r.sector === sector) && `${r.student} ${r.ra} ${r.protocol} ${r.responsible}`.toLowerCase().includes(search.toLowerCase())), [base, filter, sector, search]);
  const events = refunds.flatMap(r => r.history.map(h => ({ ...h, refund: r }))).sort((a, b) => b.at.localeCompare(a.at));
  const unread = events.filter(e => e.at > seenAt && e.actor !== profile.name).length;
  const current = refunds.find(r => r.id === selected);
  const navigate = (next: View) => { setView(next); setFilter('all'); setSector('all'); setSearch(''); setMobileMenu(false); };
  const toggleTheme = () => { const value = !dark; setDark(value); document.documentElement.classList.toggle('dark', value); localStorage.setItem('devolucoes.v1.theme', value ? 'dark' : 'light'); };
  async function saveForm(fields: Partial<Refund>) { setSaving(true); setError(''); try { const r = form !== 'new' && form ? await api(`/api/refunds/${form.id}`, 'PATCH', { action: 'resubmit', version: form.version, fields }) : await api('/api/refunds', 'POST', fields); await refresh(); setForm(null); setSelected(r.id); setToast(r.trackingUrl ? 'Solicitação salva. O link de acompanhamento está pronto para compartilhar.' : 'Solicitação salva. Abra o pedido para gerar ou atualizar o link.'); } catch (e) { setError((e as Error).message); } finally { setSaving(false); } }
  async function action(name: string, extra: Record<string, unknown>) { if (!current) return; setSaving(true); setError(''); try { let r: Refund; if (name === 'pay') { const form = new FormData(); form.set('version', String(current.version)); form.set('paidAt', String(extra.paidAt || '')); form.set('confirmed', String(extra.confirmed === true)); form.set('attachProof', String(extra.attachProof)); if (extra.file instanceof File) form.set('file', extra.file); const response = await fetch('/api/refunds/' + encodeURIComponent(current.id) + '/confirm-payment', { method: 'POST', headers: { 'Accept': 'application/json', 'X-Profile': profile.id }, credentials: 'same-origin', cache: 'no-store', body: form }); const result = await response.json(); if (!response.ok) throw Error(result.error || 'Não foi possível confirmar o pagamento.'); r = result; } else { r = await api(`/api/refunds/${current.id}`, 'PATCH', { action: name, version: current.version, ...extra }); } await refresh(); setToast(r.trackingToken && !r.trackingReady ? 'Etapa salva. Atualize o link no pedido antes de compartilhar.' : name === 'pay' ? 'Pagamento registrado. Acompanhamento atualizado.' : 'Etapa atualizada. Equipes notificadas no sistema.'); } catch (e) { setError((e as Error).message); } finally { setSaving(false); } }
  async function prepareTracking() { if (!current) return; setSaving(true); setError(''); try { await api(`/api/refunds/${current.id}/tracking`, 'POST'); await refresh(); setToast('Link de acompanhamento atualizado.'); } catch (e) { setError((e as Error).message); } finally { setSaving(false); } }
  const sidebar = <><div className="flex h-[116px] shrink-0 items-center px-5"><img src="/logo-anchieta.png" alt="Grupo Anchieta" className="h-auto w-[204px] object-contain"/></div><div className="px-5 pb-5 text-[12px] font-medium text-ink-3">Gestão de devoluções</div><nav aria-label="Navegação principal" className="space-y-1 px-3">{([{ id: 'all', label: 'Solicitações', icon: LayoutList }, { id: 'done', label: 'Concluídas', icon: CircleCheck }] as const).map(item => <motion.button key={item.id} whileTap={press} onClick={() => navigate(item.id)} aria-current={view === item.id ? 'page' : undefined} className={`relative flex w-full items-center gap-2.5 rounded-md px-3 py-3 text-left text-[13px] font-medium transition-colors ${view === item.id ? 'text-on-brand' : 'text-ink-2 hover:bg-surface-2'}`}>{view === item.id && <motion.span layoutId="sidebar-active" transition={spring} className="absolute inset-0 rounded-md bg-brand"/>}<item.icon className="relative h-4 w-4"/><span className="relative">{item.label}</span></motion.button>)}</nav><div className="mt-auto space-y-4 p-4"><Button variant="ghost" onClick={() => { setGuide(true); setMobileMenu(false); }} className="w-full justify-start px-3"><FileText className="h-4 w-4"/>Como funciona</Button><div className="rounded-xl bg-surface-2 p-3.5"><span className="text-[12px] font-medium">Ambiente de apresentação</span><p className="mt-1 text-[11.5px] leading-relaxed text-ink-3">Dados fictícios. Explore o fluxo pelos três perfis.</p></div><div className="flex items-center gap-2.5 px-1"><Avatar name={profile.name}/><div className="min-w-0"><p className="truncate text-[13px] font-medium">{profile.name}</p><p className="mt-0.5 text-[11px] text-ink-3">{profile.sector}</p></div></div></div></>;
  return <div className="flex min-h-screen bg-canvas"><aside className="sticky top-0 hidden h-screen w-[244px] shrink-0 flex-col bg-surface lg:flex">{sidebar}</aside><div className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-[64px] items-center justify-between gap-3 border-b border-hairline bg-surface/90 px-4 backdrop-blur-xl sm:px-8"><div className="flex items-center gap-3"><Button variant="ghost" onClick={() => setMobileMenu(true)} aria-label="Abrir menu" className="px-2 lg:hidden"><Menu className="h-5 w-5"/></Button><span className="hidden items-center gap-2 text-[12px] text-ink-3 sm:flex">Financeiro<ChevronRight className="h-3.5 w-3.5"/><span className="font-medium text-ink">Devoluções</span></span><span className="font-medium text-ink lg:hidden">UniAnchieta</span></div><div className="flex min-w-0 items-center gap-2 sm:gap-3"><label className="hidden text-[12px] text-ink-3 xl:block" htmlFor="profile">Perfil de apresentação</label><select id="profile" aria-label="Perfil de apresentação" value={profile.id} onChange={e => { setProfile(profiles.find(p => p.id === e.target.value)!); setSelected(null); setForm(null); setError(''); }} className="h-9 max-w-[190px] rounded-full bg-surface-2 px-3 text-[12px] font-medium sm:max-w-none"><option value="victor">Solicitante · Victor</option><option value="financeiro">Financeiro</option><option value="pagamentos">Cobranças a Pagar</option></select><Button variant="ghost" aria-label={dark ? 'Ativar tema claro' : 'Ativar tema escuro'} onClick={toggleTheme} className="hidden px-2 sm:inline-flex">{dark ? <Sun className="h-4 w-4"/> : <Moon className="h-4 w-4"/>}</Button><Button variant="ghost" aria-label={`Notificações, ${unread} não lidas`} onClick={() => setNotices(true)} className="relative px-2"><Bell className="h-4 w-4"/>{unread > 0 && <span className="absolute right-1 top-1 h-1.5 w-1.5 rounded-full bg-warn"/>}</Button></div></header>
    <main className="mx-auto max-w-[1440px] space-y-3 px-4 py-4 sm:px-8 sm:py-5"><motion.div variants={pageVariants} initial="initial" animate="animate" className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-[24px] font-semibold leading-[1.15] sm:text-[30px]">{view === 'done' ? 'Concluídas' : 'Devoluções'}</h1><p className="mt-1 text-[13px] text-ink-3">{view === 'done' ? 'Pagamentos realizados e solicitações encerradas.' : 'Todas as solicitações, do cadastro ao pagamento.'}</p></div>{profile.role === 'solicitante' && <Button variant="primary" onClick={() => { setForm('new'); setError(''); }}><Plus className="h-4 w-4"/>Nova solicitação</Button>}</div>
    <div className={`grid grid-cols-2 gap-4 py-1 ${profile.role !== 'solicitante' ? 'sm:grid-cols-3' : 'sm:grid-cols-2'} sm:py-2`}><div><span className="block font-mono text-[30px] font-medium leading-none">{active.length.toString().padStart(2, '0')}</span><span className="mt-2 block text-[12px] text-ink-3">Em andamento</span></div><div><span className="block font-mono text-[30px] font-medium leading-none">{refunds.filter(r => r.status === 'correcao').length.toString().padStart(2, '0')}</span><span className="mt-2 block text-[12px] text-ink-3">Precisam de correção</span></div>{profile.role !== 'solicitante' && <div className="col-span-2 sm:col-span-1"><span className="block font-mono text-[24px] font-medium leading-none text-money sm:text-[30px]">{money(active.reduce((sum, r) => sum + r.amount, 0))}</span><span className="mt-2 block text-[12px] text-ink-3">Valor em andamento</span></div>}</div>
    {loadError && <Callout><div className="flex items-center justify-between gap-4"><p role="alert">{loadError}</p><Button onClick={() => void refresh()}>Tentar novamente</Button></div></Callout>}
    <Card><div className="flex flex-wrap items-center justify-between gap-3 px-5 pt-3"><div className="flex flex-wrap gap-1 rounded-full bg-surface-2 p-1" aria-label="Filtrar por etapa">{[['all', 'Todas'], ['conferencia', 'Conferência'], ['pagamento', 'Pagamento'], ['correcao', 'Correções'], ['pago', 'Pagas'], ['encerrado', 'Encerradas']].filter(([id]) => view === 'all' || id === 'all').map(([id, name]) => <motion.button key={id} whileTap={press} aria-pressed={filter === id} onClick={() => setFilter(id)} className={`relative h-8 rounded-full px-3 text-[12.5px] font-medium ${filter === id ? 'text-ink' : 'text-ink-3'}`}>{filter === id && <motion.span layoutId="status-filter" transition={spring} className="absolute inset-0 rounded-full bg-surface"/>}<span className="relative">{name}<span className="ml-2 font-mono text-[10px] opacity-65">{id === 'all' ? base.length : base.filter(r => r.status === id).length}</span></span></motion.button>)}</div><Button variant="ghost" onClick={() => void refresh()} aria-label="Atualizar solicitações" className="px-2"><RefreshCw className={`h-3.5 w-3.5 ${loading ? 'animate-spin' : ''}`}/></Button></div><div className="flex flex-col gap-3 px-5 py-2 sm:flex-row"><div className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-ink-4"/><input type="search" aria-label="Buscar por RA, aluno ou protocolo" placeholder="Buscar por RA, aluno ou protocolo" value={search} onChange={e => setSearch(e.target.value)} className="h-9 w-full rounded-md bg-surface-2 pl-9 pr-8 text-[13px] outline-none focus:ring-2 focus:ring-focus"/>{search && <button aria-label="Limpar busca" onClick={() => setSearch('')} className="absolute right-2 top-2.5"><X className="h-4 w-4"/></button>}</div><Select aria-label="Filtrar por setor" value={sector} onChange={e => setSector(e.target.value)} className="sm:max-w-[190px]"><option value="all">Todos os setores</option>{sectors.map(s => <option key={s}>{s}</option>)}</Select></div>
    <div className="hidden grid-cols-[minmax(200px,2fr)_minmax(140px,1.3fr)_100px_165px_100px_28px] gap-4 border-y border-hairline px-5 py-2 text-[11px] font-medium text-ink-3 xl:grid"><span>Aluno / solicitação</span><span>Motivo</span><span className="text-right">Valor</span><span>Etapa atual</span><span>Solicitado em</span><span/></div>
    {loading ? <div className="space-y-4 p-5">{[1, 2, 3].map(i => <div key={i} className="shimmer h-14 rounded-md"/>)}</div> : filtered.length ? <div className="divide-y divide-hairline">{filtered.map(r => <motion.button key={r.id} whileTap={press} onClick={() => { setSelected(r.id); setError(''); }} className="relative grid w-full grid-cols-[1fr_auto] items-center gap-x-4 gap-y-1 px-5 py-2.5 text-left transition-colors hover:bg-surface-hover xl:grid-cols-[minmax(200px,2fr)_minmax(140px,1.3fr)_100px_165px_100px_28px]" aria-label={`Abrir solicitação de ${r.student}`}><span className="flex min-w-0 items-center gap-2"><Avatar name={r.student}/><span className="min-w-0"><span className="block truncate text-[13px] font-medium">{r.student}</span><span className="mt-0.5 block text-[11px] text-ink-3"><span className="font-mono">{r.protocol}</span> · {r.sector}</span></span></span><span className="hidden text-[12px] leading-relaxed text-ink-2 xl:block">{r.reason}</span><span className={`text-right font-mono text-[14px] font-semibold ${amountColor(r)}`}>{money(r.amount)}</span><span><StatusBadge status={r.status}/><span className="mt-0.5 block text-[11px] text-ink-3">{owner(r)}</span></span><span className="text-right text-[12px] font-semibold text-ink xl:text-left">{date(r.createdAt)}<span className="mt-0.5 block text-[11px] text-ink-3" title="Contagem de segunda a sexta, sem calendário de feriados. Prazo começa no cadastro e não reinicia na correção.">{r.status === 'pago' ? 'Devolvido · OK' : r.status === 'encerrado' ? 'Sem pagamento' : `${weekdays(r.createdAt)} ${weekdays(r.createdAt) === 1 ? "dia" : "dias"} na fila`}</span></span><ChevronRight className="hidden h-4 w-4 text-ink-4 xl:block"/></motion.button>)}</div> : <div className="flex flex-col items-center gap-3 px-6 py-16 text-center"><Inbox className="h-5 w-5 text-ink-3"/><p className="text-[13px] font-medium">Nenhuma solicitação por aqui</p><p className="text-[12px] text-ink-3">{search || filter !== 'all' || sector !== 'all' ? 'Tente outro termo ou remova os filtros.' : 'Os pedidos aparecerão aqui quando chegarem a esta etapa.'}</p>{(search || filter !== 'all' || sector !== 'all') && <Button onClick={() => { setSearch(''); setFilter('all'); setSector('all'); }}>Limpar filtros</Button>}</div>}
    <footer className="flex flex-wrap items-center justify-between gap-2 border-t border-hairline px-5 py-3 text-[11px] text-ink-3"><span>{filtered.length} solicitações</span><span className="flex items-center gap-1.5"><RefreshCw className="h-3 w-3"/>Atualização automática a cada 15 s</span></footer></Card><div className="flex items-center gap-2 text-[11px] text-ink-3"><Clock3 className="h-3.5 w-3.5"/>Prazo informado atualmente: até 15 dias úteis a partir do cadastro.</div></motion.div></main></div>
    <Overlay open={!!current && !form} title={current?.protocol ?? ''} drawer onClose={() => setSelected(null)}>{current && <RefundDetail key={`${current.id}-${current.version}`} r={current} profile={profile} saving={saving} error={error} onAction={action} onEdit={() => { setForm(current); setError(''); }} onToast={setToast} onTracking={prepareTracking}/>}</Overlay>
    <Overlay open={!!form} title={form === 'new' ? 'Nova solicitação' : 'Corrigir solicitação'} onClose={() => !saving && setForm(null)}>{form && <RefundForm key={form === 'new' ? 'new' : form.id} original={form === 'new' ? undefined : form} refunds={refunds} saving={saving} error={error} onSave={saveForm} onCancel={() => setForm(null)}/>}</Overlay>
    <Overlay open={notices} title="Notificações" drawer onClose={() => setNotices(false)}><div className="p-5"><div className="mb-4 flex items-center justify-between"><p className="text-[12px] text-ink-3">Atualizações de todas as equipes</p><Button variant="ghost" onClick={async () => { try { const data = await api('/api/notifications/read', 'POST'); setSeenAt(data.seenAt); } catch (e) { setToast((e as Error).message); } }}><CheckCheck className="h-4 w-4"/>Marcar como lidas</Button></div><div className="divide-y divide-hairline">{events.map(e => <button key={e.id} className="flex w-full items-start gap-3 py-4 text-left" onClick={() => { setNotices(false); setSelected(e.refund.id); }}><span className="mt-1 flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-surface-2"><ArrowDownLeft className="h-4 w-4"/></span><span className="flex-1"><span className="block text-[13px] font-medium">{e.title}</span><span className="mt-1 block text-[12px] text-ink-2">{e.refund.student} · {e.refund.protocol}</span><span className="mt-0.5 block text-[11px] text-ink-3">{dateTime(e.at)}</span></span>{e.at > seenAt && e.actor !== profile.name && <span className="mt-2 h-1.5 w-1.5 rounded-full bg-warn"/>}</button>)}</div></div></Overlay>
    <Overlay open={guide} title="Como funciona" onClose={() => setGuide(false)}><div className="space-y-6 p-5"><Section title="O fluxo"><div className="space-y-4">{[[ClipboardList, '1. Solicitante', 'Registra primeiro a operação no Lyceum. Depois cadastra os dados e o valor aqui.'], [Search, '2. Financeiro', 'Confere a operação, o valor e a ausência de duplicidade. Encaminha para pagamento ou indica o ajuste.'], [CircleCheck, '3. Cobranças a Pagar', 'Preenche o centro de custo, realiza o pagamento fora deste sistema e confirma aqui a data. Se houver erro, solicita correção.']].map(([Icon, title, text]) => { const I = Icon as typeof ClipboardList; return <div key={String(title)} className="flex gap-3"><I className="mt-1 h-5 w-5 shrink-0 text-ink-3"/><div><h3 className="text-[13px] font-semibold">{String(title)}</h3><p className="mt-1 text-[13px] leading-relaxed text-ink-2">{String(text)}</p></div></div>; })}</div></Section><Section title="Correções e acompanhamento"><p className="text-[13px] leading-relaxed text-ink-2">A correção volta ao setor solicitante e passa novamente pelo Financeiro. O histórico permanece completo e a data original é preservada. Todos os perfis podem consultar os pedidos e as notificações. Na ausência do atendente, outro solicitante pode assumir a correção.</p></Section><Section title="Avisos ao aluno"><p className="text-[13px] leading-relaxed text-ink-2">O link individual é gerado no cadastro e acompanha as mudanças de etapa. Os textos de e-mail e push continuam como rascunho e não são enviados. Encerramentos sem pagamento não geram aviso ao aluno; a etapa continua visível para quem abrir o link.</p></Section><Callout>Esta versão permite demonstrar o fluxo com dados fictícios e perfis simulados. Não executa transferências e não envia mensagens. Antes do uso operacional, a TI conecta os usuários institucionais e os canais de comunicação.</Callout><p className="text-[12px] text-ink-3">Meta proposta: reduzir para 1 a 5 dias úteis, após validação dos tempos por setor. A contagem visual considera segunda a sexta; feriados serão definidos no calendário institucional.</p></div></Overlay>
    <Overlay open={mobileMenu} title="Devoluções" onClose={() => setMobileMenu(false)}><div className="flex min-h-[500px] flex-col">{sidebar}</div></Overlay>
    <AnimatePresence>{toast && <motion.div role="status" variants={toastVariants} initial="initial" animate="animate" exit="exit" className="fixed bottom-5 left-4 right-4 z-[60] flex items-center gap-3 rounded-xl bg-ink px-5 py-4 text-[13px] text-canvas shadow-overlay sm:left-auto sm:max-w-md"><CheckCheck className="h-4 w-4 shrink-0"/>{toast}</motion.div>}</AnimatePresence>
  </div>;
}
